### ISSUE TITLE
Deprecate in favor of `ts-node`

### ISSUE THREAD

**Issue by blakeembrey** [pspeter3/typescript-register#15]
Hi @pspeter3!

I noticed the project is having some issues with maintenance and wanted to ask what I can do to help consolidate it into a common project? I've written and published `ts-node` which features in-memory compilation of TypeScript and an (almost fully featured) REPL. It's also support >= 1.5 versions of TypeScript, so it might be a helpful upgrade path for your users. What do you think about adding some upgrade instructions for people who are new and landing here?

**Comment by pspeter3** [comment]
That sounds good. This project actually did the same thing to another. I think upgrading should be seamless for all users.

**Comment by blakeembrey** [comment]
Would you like me to make a PR with a change to the README? What should I say apart from the obvious "deprecated - please use `ts-node`".

**Comment by pspeter3** [comment]
Sure, but I want to read through your code first to make sure that I would use it instead of this library.

**Comment by blakeembrey** [comment]
Of course, that's not a problem :smile: An extra code review is always handy (there's definitely some hacks to make functionality work - like the REPL and `.type`). If you find any issues, feel free to create something for me to fix :+1:

**Comment by ForNeVeR** [comment]
You guys should _seriously_ put the deprecation notice **everywhere**: to the github page and to the npm one.

I'm a little disappointed cause I've spent my time (only a bit of it, hopefully)  fixing #14 in this package, and only after this I've found that it is to be deprecated :(

Looking forward though to use the shiny new ts-node. It seems that gulp already supports it (for executing `Gulpfile.ts`), that's cool.

**Comment by ForNeVeR** [comment]
By the way, [ts-node repo is here](https://github.com/TypeStrong/ts-node) in case anyone need to refer to it in this thread.

**Comment by pspeter3** [comment]
@ForNeVeR sorry for this to have wasted your time

**Comment by ForNeVeR** [comment]
No bad feelings, everything is okay :)
