### ISSUE TITLE
Why are there two versions of library?

### ISSUE THREAD

**Issue by ForNeVeR** [pspeter3/typescript-register#5]
Currently there are https://github.com/pspeter3/typescript-register and https://github.com/pspeter3/typescript-require. What's the difference between them and which should be used?

I should also note that the reason may be that, for example, gulp uses old version of [interpret](https://www.npmjs.com/package/interpret) module to load *.ts files and there was `typescript-require` hardcoded there (while currently [it is `typescript-register`](https://github.com/tkellen/js-interpret/blob/master/index.js#L21)) - maybe we want to do something about that.

**Comment by pspeter3** [comment]
The second version is for the point of having compatibility with typescript-require which is not my code.

**Comment by ForNeVeR** [comment]
You should definitely write it somewhere, so newcomers won't ask the same question.

**Comment by pspeter3** [comment]
I'm planning on deleting it soon once I transition some Asana code from depending on it.
