### ISSUE TITLE
Not enough crossplatform way of defining temporary directory

### ISSUE THREAD

**Issue by ForNeVeR** [pspeter3/typescript-register#6]
Currently the cache path [is defined as](https://github.com/pspeter3/typescript-register/blob/master/index.ts#L58)

``` typescript
outDir: path.join(path.sep, "tmp", "typescript-register", process.cwd()),
```

That totally won't work on Windows and I have issues with that. For example, if my project is placed in `D:\Projects\memhub`, tsc complains: `'Could not write file \'\\tmp\\typescript-register\\D:\\Projects\\memhub/gulpfile.js\': ENOENT, no such file or directory \'D:\\tmp\\typescript-register\\D:\''`

And even worse - it creates `tmp` directory at the root of my drive.

I'd suggest to replace it with `process.env.TEMP` combined with process.cwd() processed by [sanitize-filename](https://www.npmjs.com/package/sanitize-filename) or something alike.

**Comment by pspeter3** [comment]
That sounds good to me. I wasn't thinking about Windows when I wrote this beyond `path.join`. My apologies.
