### ISSUE TITLE
How to fork?

### ISSUE THREAD

**Issue by tkrotoff** [pspeter3/typescript-register#9]
I've forked your code in order to force TypeScript 1.5.0-beta.

Problem is when I reference [my fork](https://github.com/tkrotoff/typescript-register) in my project package.json, the resulting typescript-register does not contain index.js nor index.ts (and thus it fails).

I guess there is a small step that I'm missing.
I was expecting that typescript-register index.ts would be listed inside [package.json](https://github.com/tkrotoff/typescript-register/blob/master/package.json#L6) and that a [postinstall npm task](https://github.com/tkrotoff/typescript-register/blob/master/package.json#L11) would be run each time a npm install/update is performed in order to generate the true index.js.

**Comment by pspeter3** [comment]
You need to compile it and check the compiled code in to fork.

**Comment by tkrotoff** [comment]
How did you managed to not have to include index.js inside your own repo?

**Comment by pspeter3** [comment]
It's git ignored but included when I publish to npm, See https://github.com/Asana/typescript-starter for more information

**Comment by tkrotoff** [comment]
I see. I'm so used to Bower where the package IS the Git repo. npm stores its own version (most of the time the files from the Git repo - not the case here) like Ruby gems.
If I write `"typescript-require": "pspeter3/typescript-require"` inside my package.json for example it won't work.
